### ISSUE TITLE
fails to build on Raspbian

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/to_lab#21]
**Describe the bug**
Building to_lab under Raspbian (a Debian variant for Raspberry Pi SBC's) fails due to alignment issues.

```
/home/pi/cFS/apps/to_lab/fsw/src/to_lab_app.c:408:25: error: cast increases required alignment of target type [-Werror=cast-align]
     CFE_SB_TimeStampMsg((CFE_SB_Msg_t *) &to_hk_status);
                         ^
/home/pi/cFS/apps/to_lab/fsw/src/to_lab_app.c:409:20: error: cast increases required alignment of target type [-Werror=cast-align]
     CFE_SB_SendMsg((CFE_SB_Msg_t *)&to_hk_status);
                    ^
```

**To Reproduce**
Build on Raspbian.

**Expected behavior**
No compiler errors.

**Code snips**
If applicable, add references to the software.

**System observed on:**
Raspberry Pi Zero W

**Additional context**

**Reporter Info**
Christopher.D.Knight@nasa.gov

**Comment by jphickey** [comment]
I have fixes for these!  These are the same general issue as in nasa/cfe#313.  If you want you can assign this to me and just turn off -Wcast-align in your build for now.

**Comment by skliper** [comment]
@astrogeco Did this get fixed with your last IC?  Maybe a link was missed?

**Comment by astrogeco** [comment]
> @astrogeco Did this get fixed with your last IC? Maybe a link was missed?

Yep, we just didn't link it using the "fix" nomenclature. I'll close it.

**Comment by astrogeco** [comment]
FIxed by https://github.com/nasa/to_lab/pull/24
