### ISSUE TITLE
TO_subsciption_t typo

### ISSUE THREAD

**Issue by skliper** [nasa/to_lab#3]
Originated by kseywald (130 on babelfish):

It looks like "to_subsciption" ought to be "to_subscription". The typo occurs in the following locations:
apps/to_lab/fsw/platform_inc/to_lab_sub_table.h:38:static TO_subsciption_t TO_SubTable[] =
apps/to_lab/fsw/platform_inc/to_lab_sub_table.h:57: /* cFE Core subsciptions */
apps/to_lab/fsw/src/to_lab_app.c:194: for (i=0; (i < (sizeof(TO_SubTable)/sizeof(TO_subsciption_t))); i++)
apps/to_lab/fsw/src/to_lab_app.c:472: for (i=0; (i < (sizeof(TO_SubTable)/sizeof(TO_subsciption_t))); i++)
apps/to_lab/fsw/src/to_lab_msg.h:84: } TO_subsciption_t;

**Comment by skliper** [comment]
Should also notify originator when complete (see babelfish).

**Comment by avan989** [comment]
I can do this.
