### ISSUE TITLE
TO_LAB App only receiving NOOP commands

### ISSUE THREAD

**Issue by atk5025** [nasa/to_lab#33]
**Describe the bug**
After updating to the most recent cFS packages (git pull) and recursively updating the submodules, all commands from GroundSystem.py to TO_LAB are being interpreted as NOOPS. First saw this with requesting output enabled but then verified that all commands are being seen as NOOPS. Outputs of git pull are below capturing 

GroundSystem.py Output:
Host: 127.0.0.1
Port: 1234
Pkt ID: 0x1880
sending data to '127.0.0.1' (IP : 127.0.0.1); port 1234
Data to send:
0x18 0x80 0xC0 0x00 0x00 0x01 0x00 0x06 

CFE Output
EVS Port1 42/1/CFE_TIME 21: Stop FLYWHEEL
EVS Port1 42/1/TO_LAB_APP 18: No-op command

Same command with previous build yields the below and telemetry beings to flow.
EVS Port1 42/1/CFE_TIME 21: Stop FLYWHEEL
EVS Port1 42/1/TO_LAB_APP 3: TO telemetry output enabled for IP 

**To Reproduce**
git pull to latest and run both cFE and GroundSystem.py

**Expected behavior**
Expected a TO_OUTPUT_ENABLE 

**Code snips**
allen@akum-home-lt:~/repos/cFS/missionxyz$ git pull
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 65 (delta 12), reused 20 (delta 11), pack-reused 43
Unpacking objects: 100% (65/65), done.
From https://github.com/nasa/cFS
   69e18e5..788b8d6  master                -> origin/master
 * [new branch]      gh-pages              -> origin/gh-pages
 * [new branch]      integration-candidate -> origin/integration-candidate
Fetching submodule apps/ci_lab
From https://github.com/nasa/ci_lab
 * [new branch]      integration-candidate -> origin/integration-candidate
   3ad9a10..fe9e3ef  master                -> origin/master
Fetching submodule apps/sample_app
From https://github.com/nasa/sample_app
 * [new branch]      integration-candidate -> origin/integration-candidate
   1f84f20..b956292  master                -> origin/master
Fetching submodule apps/sample_lib
From https://github.com/nasa/sample_lib
 * [new branch]      integration-candidate -> origin/integration-candidate
   f499730..33efec3  master                -> origin/master
Fetching submodule cfe
From https://github.com/nasa/cFE
 * [new branch]      integration-candidate -> origin/integration-candidate
   d6d944c..60a5f65  master                -> origin/master
Fetching submodule osal
From https://github.com/nasa/osal
 * [new branch]      integration-candidate -> origin/integration-candidate
   2284a6f..7d9c4c8  master                -> origin/master
Fetching submodule psp
From https://github.com/nasa/PSP
 * [new branch]      integration-candidate -> origin/integration-candidate
   621abba..12e2607  master                -> origin/master
Fetching submodule tools/cFS-GroundSystem
From https://github.com/nasa/cFS-GroundSystem
 * [new branch]      integration-candidate -> origin/integration-candidate
   c982339..9d4b155  master                -> origin/master
Updating 69e18e5..788b8d6
Fast-forward
 .lgtm.yml              |  31 ++++++++++++++++---------------
 .travis.yml            | 100 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------
 README.md              |  10 ++++------
 apps/ci_lab            |   2 +-
 apps/sample_app        |   2 +-
 apps/sample_lib        |   2 +-
 cfe                    |   2 +-
 osal                   |   2 +-
 psp                    |   2 +-
 tools/cFS-GroundSystem |   2 +-
 10 files changed, 120 insertions(+), 35 deletions(-)

**System observed on:**
 - Docker build
 - OS: Ubuntu

**Additional context**
N/A

**Reporter Info**
Allen Kummer - Self

**Comment by atk5025** [comment]
Non-functional version is self reporting the following base configurations. 

EVS Port1 42/1/CFE_ES 3: No-op command. Versions:cFE 6.7.12.0, OSAL 5.0.11.0, PSP 1.4.8.0

Also, it looks like in my environment, all applications are only responding with NOOPS. So the problem is probably outside TO_LAB and either CI_LAB or other core components on this build/target.

**Comment by jphickey** [comment]
please confirm that you have done a `git submodule update` after pulling the cFS repo.  This is a possible symptom of changing the endianness of the secondary header if you cross versions between CFE and cmdutil/ground system

**Comment by jphickey** [comment]
Also important to note that the `integration-candidate` branch is not necessarily stable as it is the think being tested - please always use `master` unless you are intending to check the integration of the latest changes.

**Comment by atk5025** [comment]
@jphickey Thanks for your suggestions. Did command code endianness change in the last month somewhere? I was guessing this would be a stable parameter and only changing for different processor types.

Seems the crossing version endianness may be the root here. I seem to have ended up with differing combinations of endianness between a couple different builds I've done recently. Running the GroundSystem.py seems to send out out BE when it looks like now I'm expecting to receive the command code in LE. 

When I go use the to-enable-tlm.sh script, it's sending the command code in LE so that's working. 

Regarding `integration-candidate`, from what I can see in the update/pull I did previously, I'm pulling master for all repositories. I do see numerous references to the `integration-candidate`, but I thought that was just saying that while I'm on master, it was also pulling down the latest information for that branch but I could be misinterpreting that.

allen@akum-home-lt:~/repos/cFS/missionxyz$ git submodule update
allen@akum-home-lt:~/repos/cFS/missionxyz$ git pull
Already up to date.
allen@akum-home-lt:~/repos/cFS/missionxyz$ git submodule update
allen@akum-home-lt:~/repos/cFS/missionxyz$ git submodule upitdate --recursive 
allen@akum-home-lt:~/repos/cFS/missionxyz$

**Comment by jphickey** [comment]
Yes, the definition of the secondary header did change recently.  GSFC does not actually define this field as a uint16, it defines it as an 8-bit command code and 8-bit checksum, and the structure in the code was recently updated according to this definition.

Just double check to be sure you are running a matching commit in all submodules, and run a "make distclean" (or just fully remove your build dir) to be absolutely sure you aren't running an old binary somehow.

**Comment by skliper** [comment]
Probably still using the old cmdUtil executable.  Note that cFS-GroundSystem looks for the compiled version of cmdUtil in `cFS-GroundSystem/Subsystems/cmdUtil`, so you need to rebuild it there.

**Comment by skliper** [comment]
Ticket https://github.com/nasa/cFS-GroundSystem/issues/61 would resolve this.

**Comment by atk5025** [comment]
I have confirmed this came from mismatched cmdUtil. I have been successful after deleting the build folder and rebuilding.
